### ISSUE TITLE
502 Gateway Error

### ISSUE THREAD

**Issue by thenotoriousllama** [irajneeshgupta/shipstation#2]
Hello,

We are receiving a 502 Gateway Error when trying to link ShipStation in 2.4.1 with this patch.

**Comment by HudsonWY** [comment]
We re also getting the same error:

We received an error testing the Magento store: The remote server returned an error: (502) Bad Gateway.

**Comment by irajneeshgupta** [comment]
use the latest release of shipstation , it will fix your issues.
thanks.
